apiVersion: v1
kind: ReplicationController
metadata:
 name: minion
spec:
 replicas: 1
 selector:
  app: minion
 template:
  metadata:
   labels:
    app: minion
  spec:
   containers:
   - name: minion
     image: sysu2019dsfnw/server
     imagePullPolicy: IfNotPresent
     command: ["python", "minion.py"]
     ports:
     - containerPort: 8888
