apiVersion: v1
kind: Pod
metadata:
 name: minion04
spec:
 containers:
 - name: minion0401
   image: dfs-base
   imagePullPolicy: IfNotPresent
   command: ["/bin/bash","-ce","tail -f /dev/null"]
   ports:
   - containerPort: 8888
 - name: minion0402
   image: dfs-base
   imagePullPolicy: IfNotPresent
   command: ["/bin/bash","-ce","tail -f /dev/null"]
   ports:
   - containerPort: 28888
 - name: minion0403
   image: dfs-base
   imagePullPolicy: IfNotPresent
   command: ["/bin/bash","-ce","tail -f /dev/null"]
   ports:
   - containerPort: 38888