apiVersion: v1
kind: Service
metadata:
 name: minion4
spec:
 type: NodePort
 ports:
  - port: 8888
    name: port1
    nodePort: 32141
  - port: 28888
    name: port2
    nodePort: 32142
  - port: 38888
    name: port3
    nodePort: 32143
 selector:
  app: minion4