apiVersion: v1
kind: ReplicationController
metadata:
 name: server
spec:
 replicas: 1
 selector:
  app: server
 template:
  metadata:
   labels:
    app: server
  spec:
   containers:
   - name: server
     image: sysu2019dsfnw/server
     imagePullPolicy: IfNotPresent
     command: ["python", "master.py"]
     ports:
     - containerPort: 2131
